def get_race_code_from_name(race_name):
    if not race_name: return "UNK"
    r_name = race_name.lower()
    if "bahrain" in r_name: return "BHR"
    if "saudi" in r_name: return "SAU"
    if "australia" in r_name: return "AUS"
    if "japan" in r_name: return "JPN"
    if "china" in r_name: return "CHN"
    if "miami" in r_name: return "MIA"
    if "imola" in r_name or "emilia" in r_name: return "EMI"
    if "monaco" in r_name: return "MON"
    if "canada" in r_name: return "CAN"
    if "spain" in r_name: return "ESP"
    if "austria" in r_name: return "AUT"
    if "britain" in r_name: return "GBR"
    if "hungary" in r_name: return "HUN"
    if "belgium" in r_name: return "BEL"
    if "netherlands" in r_name: return "NED"
    if "italy" in r_name: return "ITA"
    if "azerbaijan" in r_name: return "AZE"
    if "singapore" in r_name: return "SIN"
    if "united states" in r_name or "usa" in r_name: return "USA"
    if "mexico" in r_name: return "MEX"
    if "brazil" in r_name: return "BRA"
    if "vegas" in r_name: return "LVG"
    if "qatar" in r_name: return "QAT"
    if "abu dhabi" in r_name: return "ABU"
    return "UNK"
